# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-scisoseq-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # TODO nf-core: Add required software dependencies here
  - bioconda::multiqc=1.7
  - conda-forge::r-markdown=1.1
  - conda-forge::r-base=3.6.1
  - python=2.7
  - conda-forge::biopython=1.74 # biopython docs suggest using conda-forge 
  - isoseq3=3.2
  - minimap2=2.17
  - samtools=1.9
  - bamtools=2.5
  - pbcoretools=0.2.4 # needed for merging SMRT cells
  - lima=1.10
  # - pbccs # only needed to do ccs calling
  - pip:
    - git+https://github.com/Magdoll/cDNA_Cupcake.git@Py2_v8.7.x
 # SQANTI2 deps
  - bioconda::pysam=0.15
  - psutil=5.6
  - bx-python=0.8
  - bcbiogff=0.6
  - gffread=0.11
  # http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/gtfToGenePred - saved to bin/
